// Simple PDF Generator - creates HTML that can be printed to PDF
// For production, use pdfkit or puppeteer

export function generateQuoteHTML(quote: any): string {
  const items = quote.items.map((item: any) => `
    <tr>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">
        <strong>${item.name}</strong>
        ${item.description ? `<br><small style="color: #6b7280;">${item.description}</small>` : ''}
      </td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">${item.quantity}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right;">€${item.unitPrice.toFixed(2)}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: right; font-weight: bold;">€${item.total.toFixed(2)}</td>
    </tr>
  `).join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Quote ${quote.quoteNumber}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.5; }
    .container { max-width: 800px; margin: 0 auto; padding: 40px; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; }
    .logo { font-size: 24px; font-weight: bold; color: #dc2626; }
    .quote-info { text-align: right; }
    .quote-number { font-size: 18px; font-weight: bold; }
    .quote-date { color: #6b7280; }
    .client { margin-bottom: 40px; }
    .client h3 { font-size: 14px; color: #6b7280; margin-bottom: 8px; }
    .items { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
    .items th { padding: 12px; text-align: left; background: #f9fafb; border-bottom: 2px solid #e5e7eb; font-size: 12px; text-transform: uppercase; color: #6b7280; }
    .totals { margin-left: auto; width: 300px; }
    .totals-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e5e7eb; }
    .totals-row.total { font-size: 20px; font-weight: bold; border-bottom: none; padding-top: 16px; }
    .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="logo">Quote Engine</div>
      <div class="quote-info">
        <div class="quote-number">${quote.quoteNumber}</div>
        <div class="quote-date">${new Date(quote.generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
      </div>
    </div>
    
    <div class="client">
      <h3>Bill To:</h3>
      <div><strong>${quote.clientName}</strong></div>
      ${quote.clientEmail ? `<div>${quote.clientEmail}</div>` : ''}
    </div>
    
    <table class="items">
      <thead>
        <tr>
          <th>Item</th>
          <th style="text-align: center;">Qty</th>
          <th style="text-align: right;">Unit Price</th>
          <th style="text-align: right;">Total</th>
        </tr>
      </thead>
      <tbody>
        ${items}
      </tbody>
    </table>
    
    <div class="totals">
      <div class="totals-row">
        <span>Subtotal</span>
        <span>€${quote.subtotal.toFixed(2)}</span>
      </div>
      ${quote.buffer > 0 ? `
      <div class="totals-row">
        <span>Buffer</span>
        <span>€${quote.buffer.toFixed(2)}</span>
      </div>
      ` : ''}
      ${quote.tax > 0 ? `
      <div class="totals-row">
        <span>Tax</span>
        <span>€${quote.tax.toFixed(2)}</span>
      </div>
      ` : ''}
      <div class="totals-row total">
        <span>Total</span>
        <span>€${quote.total.toFixed(2)}</span>
      </div>
    </div>
    
    <div class="footer">
      <p>Thank you for your business!</p>
      <p>Generated by Quote Engine</p>
    </div>
  </div>
</body>
</html>
  `.trim();
}
